# -*- coding: utf-8 -*-
"""AssessmentDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GmcAAw0OCiSTia0FwjhxQqp2DyTXKnW
"""

!pip install mysql.connector

import mysql.connector

mydb = mysql.connector.connect(
  host="sql8.freesqldatabase.com",
  user="sql8629511",
  password="piCnnyCvCH"
)
mycursor = mydb.cursor()

##Create db /already available
#mycursor.execute("CREATE DATABASE DreamlandManor")

#Check db was created
mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

##Connect to db
mydb = mysql.connector.connect(
  host="sql8.freesqldatabase.com",
  user="sql8629511",
  password="piCnnyCvCH",
  database="sql8629511"
)

mycursor = mydb.cursor()

##Create tables
mycursor.execute("CREATE TABLE Hotel (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), description varchar(255), rating varchar(255), email varchar(255),country varchar(255), city varchar(255), street varchar(255), phone varchar(255))")
mycursor.execute("CREATE TABLE Rooms (id INT AUTO_INCREMENT PRIMARY KEY, hotelId integer, shortname varchar(255), status varchar(255), price float, type varchar(255), capacity integer, desription varchar(255))")
mycursor.execute("CREATE TABLE Amenities (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))")
mycursor.execute("CREATE TABLE Users (id INT AUTO_INCREMENT PRIMARY KEY, firstName varchar(255), lastName varchar(255))")
mycursor.execute("CREATE TABLE Gallery (id INT AUTO_INCREMENT PRIMARY KEY, roomId integer, type varchar(255), url varchar(255))")
mycursor.execute("CREATE TABLE RoomsAmentities (roomid INT AUTO_INCREMENT PRIMARY KEY, amenityID integer)")
mycursor.execute("CREATE TABLE Reservations (id INT AUTO_INCREMENT PRIMARY KEY, roomId integer, userId integer, checkin date, checkout date, status varchar(255), notes varchar(255), FOREIGN KEY (roomId) REFERENCES Rooms (id))")
mycursor.execute("CREATE TABLE UsersIdentities (userId INT AUTO_INCREMENT PRIMARY KEY, identityId integer, FOREIGN KEY (userId) REFERENCES Users (id))")
mycursor.execute("CREATE TABLE Billing (id INT AUTO_INCREMENT PRIMARY KEY, reservationId integer, userId integer, billNumber varchar(255), amount float, status varchar(255), billed date, paid date, paymentReference varchar(255), receiptNumber varchar(255))")
mycursor.execute("CREATE TABLE Identities (id INT AUTO_INCREMENT PRIMARY KEY, hotelId integer, email varchar(255), password varchar(255), role varchar(255))")

#Check tables were created
mycursor.execute("SHOW TABLES")
for x in mycursor:
  print(x)

mycursor.execute("ALTER TABLE Rooms ADD FOREIGN KEY (hotelId) REFERENCES Hotel (id)")

mycursor.execute("ALTER TABLE Identities ADD FOREIGN KEY (hotelId) REFERENCES Hotel (id)")

mycursor.execute("ALTER TABLE UsersIdentities ADD FOREIGN KEY (userId) REFERENCES Users (id)")

mycursor.execute("ALTER TABLE UsersIdentities ADD FOREIGN KEY (identityId) REFERENCES Identities (id)")

mycursor.execute("ALTER TABLE RoomsAmentities ADD FOREIGN KEY (roomId) REFERENCES Rooms (id)")

mycursor.execute("ALTER TABLE RoomsAmentities ADD FOREIGN KEY (amenityID) REFERENCES Amenities (id)")

mycursor.execute("ALTER TABLE Reservations ADD FOREIGN KEY (roomId) REFERENCES Rooms (id)")

mycursor.execute("ALTER TABLE Reservations ADD FOREIGN KEY (userId) REFERENCES Users (id)")

mycursor.execute("ALTER TABLE Billing ADD FOREIGN KEY (reservationId) REFERENCES Reservations (id)")

mycursor.execute("ALTER TABLE Gallery ADD FOREIGN KEY (roomId) REFERENCES Rooms (id)")



#Populating tables with data
#install the faker package
!pip install Faker

# Import the necessary packages
from faker import Faker
import datetime

# Create an instance of the Faker generator
fake = Faker()

# Truncate existing tables
mycursor.execute("SET FOREIGN_KEY_CHECKS = 0")
mycursor.execute("TRUNCATE TABLE Hotel")
mycursor.execute("TRUNCATE TABLE Rooms")
mycursor.execute("TRUNCATE TABLE Amenities")
mycursor.execute("TRUNCATE TABLE Users")
mycursor.execute("TRUNCATE TABLE Gallery")
mycursor.execute("TRUNCATE TABLE RoomsAmentities")
mycursor.execute("TRUNCATE TABLE Reservations")
mycursor.execute("TRUNCATE TABLE UsersIdentities")
mycursor.execute("TRUNCATE TABLE Billing")
mycursor.execute("TRUNCATE TABLE Identities")
mycursor.execute("SET FOREIGN_KEY_CHECKS = 1")

hotel_name = "Dreamland Manor"
hotel_description = fake.sentence()
hotel_rating = fake.random_int(min=1, max=5)
hotel_email = fake.email()
hotel_country = fake.country()
hotel_city = fake.city()
hotel_street = fake.street_address()
hotel_phone = fake.phone_number()
mycursor.execute(f"INSERT INTO Hotel (name, description, rating, email, country, city, street, phone) VALUES ('{hotel_name}', '{hotel_description}', '{hotel_rating}', '{hotel_email}', '{hotel_country}', '{hotel_city}', '{hotel_street}', '{hotel_phone}')")


mycursor.execute("SELECT * FROM Hotel")

hotel = mycursor.fetchall()
hotel_id = hotel[0][0]
print(hotel_id)
for x in hotel:
  print(x)

# Create and execute insert statements to populate the tables with 1000 records
for _ in range(10):
    # Insert statement for Rooms table
    room_hotel_id = hotel_id #forign key to hotel
    room_shortname = fake.random_letter() + fake.random_letter()
    room_status = fake.random_element(elements=('Available', 'Occupied', 'Maintenance'))
    room_price = fake.random_int(min=50, max=200)
    room_type = fake.random_element(elements=('Standard', 'Deluxe', 'Suite'))
    room_capacity = fake.random_int(min=1, max=4)
    room_description = fake.sentence()
    roomcursor = mydb.cursor()
    roomcursor.execute(f"INSERT INTO Rooms (hotelId, shortname, status, price, type, capacity, desription) VALUES ('{room_hotel_id}', '{room_shortname}', '{room_status}', '{room_price}', '{room_type}', '{room_capacity}', '{room_description}')")

    # Insert statement for Gallery table
    gallery_room_id = roomcursor.lastrowid
    gallery_type = fake.random_element(elements=('Image', 'Video'))
    gallery_url = fake.url()
    mycursor.execute(f"INSERT INTO Gallery (roomId, type, url) VALUES ('{gallery_room_id}', '{gallery_type}', '{gallery_url}')")

    # Insert statement for Amenities table
    amenity_name = fake.word()
    amenitycursor = mydb.cursor()
    amenitycursor.execute(f"INSERT INTO Amenities (name) VALUES ('{amenity_name}')")

    # Insert statement for RoomsAmentities table
    mycursor.execute(f"INSERT INTO RoomsAmentities (roomid, amenityID) VALUES ('{roomcursor.lastrowid}', '{amenitycursor.lastrowid}')")

    # Insert statement for Users table
    user_first_name = fake.first_name()
    user_last_name = fake.last_name()
    usercursor = mydb.cursor()
    usercursor.execute(f"INSERT INTO Users (firstName, lastName) VALUES ('{user_first_name}', '{user_last_name}')")



    # Insert statement for Reservations table
    reservation_room_id = roomcursor.lastrowid
    reservation_user_id = usercursor.lastrowid
    reservation_checkin = fake.date_between(start_date='-1y', end_date='+1y')
    reservation_checkout = fake.date_between_dates(date_start=reservation_checkin, date_end=reservation_checkin+datetime.timedelta(days=5))
    reservation_status = fake.random_element(elements=('Confirmed', 'Pending', 'Cancelled'))
    reservation_notes = fake.sentence()
    reservationcursor = mydb.cursor()
    reservationcursor.execute(f"INSERT INTO Reservations (roomId, userId, checkin, checkout, status, notes) VALUES ('{reservation_room_id}', '{reservation_user_id}', '{reservation_checkin}', '{reservation_checkout}', '{reservation_status}', '{reservation_notes}')")

    # Insert statement for UsersIdentities table
    #user_identity_id = fake.random_int(min=1, max=100)
    #mycursor.execute(f"INSERT INTO UsersIdentities (userId, identityId) VALUES ('{reservation_user_id}', '{user_identity_id}')")

    # Insert statement for Billing table
    billing_reservation_id = reservationcursor.lastrowid
    billing_user_id = usercursor.lastrowid
    billing_number = fake.random_number(digits=6)
    billing_amount = fake.random_int(min=100, max=500)
    billing_status = fake.random_element(elements=('Paid', 'Unpaid'))
    billing_billed = fake.date_between(start_date='-1y', end_date='today')
    billing_paid = fake.date_between_dates(date_start=billing_billed, date_end=billing_billed+datetime.timedelta(days=10))
    billing_reference = fake.random_number(digits=6)
    billing_receipt = fake.random_number(digits=6)
    mycursor.execute(f"INSERT INTO Billing (reservationId, userId, billNumber, amount, status, billed, paid, paymentReference, receiptNumber) VALUES ('{billing_reservation_id}', '{billing_user_id}', '{billing_number}', '{billing_amount}', '{billing_status}', '{billing_billed}', '{billing_paid}', '{billing_reference}', '{billing_receipt}')")

    # Insert statement for Identities table
    identity_hotel_id = hotel_id
    identity_email = fake.email()
    identity_password = fake.password()
    identity_role = fake.random_element(elements=('Admin', 'Employee','Guest'))
    mycursor.execute(f"INSERT INTO Identities (hotelId, email, password, role) VALUES ('{identity_hotel_id}', '{identity_email}', '{identity_password}', '{identity_role}')")

# Commit the changes to the database
mydb.commit()

#check if all table
# Check and count records in each table

# Hotel table
mycursor.execute("SELECT COUNT(*) FROM Hotel")
hotel_count = mycursor.fetchone()[0]
print("Hotel Count:", hotel_count)

# Rooms table
mycursor.execute("SELECT COUNT(*) FROM Rooms")
rooms_count = mycursor.fetchone()[0]
print("Rooms Count:", rooms_count)

# Amenities table
mycursor.execute("SELECT COUNT(*) FROM Amenities")
amenities_count = mycursor.fetchone()[0]
print("Amenities Count:", amenities_count)

# Users table
mycursor.execute("SELECT COUNT(*) FROM Users")
users_count = mycursor.fetchone()[0]
print("Users Count:", users_count)

# Gallery table
mycursor.execute("SELECT COUNT(*) FROM Gallery")
gallery_count = mycursor.fetchone()[0]
print("Gallery Count:", gallery_count)

# RoomsAmentities table
mycursor.execute("SELECT COUNT(*) FROM RoomsAmentities")
rooms_amenities_count = mycursor.fetchone()[0]
print("RoomsAmenities Count:", rooms_amenities_count)

# Reservations table
mycursor.execute("SELECT COUNT(*) FROM Reservations")
reservations_count = mycursor.fetchone()[0]
print("Reservations Count:", reservations_count)

# UsersIdentities table
mycursor.execute("SELECT COUNT(*) FROM UsersIdentities")
users_identities_count = mycursor.fetchone()[0]
print("UsersIdentities Count:", users_identities_count)

# Billing table
mycursor.execute("SELECT COUNT(*) FROM Billing")
billing_count = mycursor.fetchone()[0]
print("Billing Count:", billing_count)

# Identities table
mycursor.execute("SELECT COUNT(*) FROM Identities")
identities_count = mycursor.fetchone()[0]
print("Identities Count:", identities_count)

# Fetch records from each table
# Hotel table
mycursor.execute("SELECT * FROM Hotel")
hotel_records = mycursor.fetchall()
print("Hotel Records:")
for record in hotel_records:
    print(record)

# Rooms table
mycursor.execute("SELECT * FROM Rooms")
rooms_records = mycursor.fetchall()
print("Rooms Records:")
for record in rooms_records:
    print(record)

# Amenities table
mycursor.execute("SELECT * FROM Amenities")
amenities_records = mycursor.fetchall()
print("Amenities Records:")
for record in amenities_records:
    print(record)

# Users table
mycursor.execute("SELECT * FROM Users")
users_records = mycursor.fetchall()
print("Users Records:")
for record in users_records:
    print(record)

# Gallery table
mycursor.execute("SELECT * FROM Gallery")
gallery_records = mycursor.fetchall()
print("Gallery Records:")
for record in gallery_records:
    print(record)


# Reservations table
mycursor.execute("SELECT * FROM Reservations")
reservations_records = mycursor.fetchall()
print("Reservations Records:")
for record in reservations_records:
    print(record)

# UsersIdentities table
mycursor.execute("SELECT * FROM UsersIdentities")
users_identities_records = mycursor.fetchall()
print("UsersIdentities Records:")
for record in users_identities_records:
    print(record)

# Billing table
mycursor.execute("SELECT * FROM Billing")
billing_records = mycursor.fetchall()
print("Billing Records:")
for record in billing_records:
    print(record)

# Identities table
mycursor.execute("SELECT * FROM Identities")
identities_records = mycursor.fetchall()
print("Identities Records:")
for record in identities_records:
    print(record)